<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O5FPK5O" failures="1" tests="1" name="com.TestCases.Runner" time="4.500" errors="0" timestamp="2025-06-02T20:28:05 IST" skipped="0">
  <testcase classname="com.TestCases.Runner" name="runScenario" time="4.500">
    <failure message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.TestCases.SauceDemo.validate_user_login_by_checking_url(SauceDemo.java:40)
at âœ½.validate user login by checking url.(file:///C:/Users/QST/Downloads/Staff%20Room%20Lecture%20code%2018-5-2025/Automtion_8.00_to_9.30/TestCaseInGerkinLanguage/SauceDemo.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.TestCases.Runner -->
